# Generated by Django 5.0 on 2024-02-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobBazzar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
