# Generated by Django 5.0 on 2024-03-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobBazzar', '0004_alter_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=5)),
                ('experience', models.CharField(max_length=100)),
                ('passingYear', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('cgpa', models.CharField(max_length=10)),
                ('skills', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('projects', models.CharField(max_length=400)),
                ('achievements', models.CharField(max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
            ],
        ),
    ]
