# Generated by Django 5.0 on 2024-03-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobBazzar', '0008_alter_profile_experience_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('founded', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=40)),
                ('primary_industry', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=1000)),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='projects',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
