# Generated by Django 5.0 on 2024-03-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobBazzar', '0010_remove_job_id_job_email_job_job_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_id',
            new_name='j_id',
        ),
    ]
