# Generated by Django 5.0 on 2024-03-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobBazzar', '0011_rename_job_id_job_j_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='email',
        ),
        migrations.AddField(
            model_name='job',
            name='emails',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='j_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
