# Generated by Django 5.0 on 2024-03-14 07:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobBazzar', '0012_remove_job_email_job_emails_alter_job_j_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='j_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='job',
            name='emails',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
