# Generated by Django 5.0 on 2024-03-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobBazzar', '0013_rename_j_id_job_id_alter_job_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='current_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
