# Generated by Django 5.0 on 2024-03-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobBazzar', '0014_alter_job_current_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skill1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skill2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skill3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
