# Generated by Django 5.0 on 2024-03-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobBazzar', '0015_job_skill1_job_skill2_job_skill3'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
