# Generated by Django 5.0 on 2024-03-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobBazzar', '0017_application_alter_job_id_alter_profile_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='Pending', max_length=40),
        ),
    ]
